### ISSUE TITLE
Note Formatting Update - User Guide

### ISSUE THREAD

**Issue by EmilyNecciai** [Appboy/braze-docs#141]
# Submit an Issue
**Describe the Problem:**
Legacy formatting for the [User Guide](https://www.braze.com/docs/user_guide/introduction/) had some contributors writing notes in an inconsistent manner. Please replace all incorrect "notes" with our new **Alert formatting**. 

**Incorrect:** 

- `Note:`
- `__Note:__`
- `_Note:_`
- `__Note__:`
- `**Note:**`
- `Please note that...`
- `> Note that`

You'll probably find other variations, too.

**Correct:** 
Use Alert formatting found here: https://github.com/Appboy/braze-docs/wiki/Special-Formatting#long-alert-test

_Example:_
{% alert important %}
This is an important alert. 
{% endalert %}

Use context to determine which alert type you should use (important, note, warning, update, etc.). Sometimes, you may even find that you don't need to format things as alerts and just transition them back into typical content. 

_Final product:_
All notes will appear in variations as shown below upon render.
![Screen Shot 2019-09-30 at 8 06 52 AM](https://user-images.githubusercontent.com/25353255/65877288-4920ed80-e359-11e9-8b58-e77c561ce78f.png)

**Comment by mgroovyank** [comment]
@EmilyNecciai can I work on this?

**Comment by mgroovyank** [comment]
@EmilyNecciai Thank you.
