### ISSUE TITLE
API Docs New Formatting

### ISSUE THREAD

**Issue by EmilyNecciai** [Appboy/braze-docs#148]
# Submit an Issue
**Describe the Problem:**
Format the API Docs ([email templates](https://www.braze.com/docs/api/endpoints/email_templates/#email-templates), [email sync](https://www.braze.com/docs/api/endpoints/email_sync/), [messaging](https://www.braze.com/docs/api/endpoints/messaging/), [export](https://www.braze.com/docs/api/endpoints/export/), [subscription groups](https://www.braze.com/docs/api/endpoints/subscription_group_api/), and [user data](https://www.braze.com/docs/api/endpoints/user_data/))  in such a way that can be easily used in a js template. Will provide details & suggested format soon.

Language: [YAML/Front Matter](https://jekyllrb.com/docs/front-matter/) - See [glossaries](https://raw.githubusercontent.com/Appboy/braze-docs/develop/_docs/_user_guide/data_and_analytics/report_metrics.md) for example.
https://github.com/Appboy/braze-docs/blob/develop/_docs/_user_guide/data_and_analytics/report_metrics.md

To Do: 
- [ ] Construct new format in new .md file
- [ ] Clean up text
- [ ] Make parameters consistent (check out Parameter's library - make that consistent, too)

## Requested Components: 
These are the minimum that these docs must account for. If you feel the need to add more, please note that for our review on the 17th. 

### POST

- Endpoint name (will send list)
- Endpoint URL
- Method (POST, GET, Filter, Object) - obviously this will be all POST
- Description (write your own based on current docs)
- Response Details
- Query Parameters
- Query Example
- Response Body Parameters
- Errors
- Corresponding Link to [Swagger](https://www.braze.com/docs/api/interactive/)
- Glossary Tags (see far below)

##### Example
```
endpoint: Create Email Template
     endpoint_url: /templates/email/create
     method: POST
     description: Use the Email Template REST APIs to programmatically manage the email templates that you have stored on the Braze dashboard, on the Templates & Media page. Braze provides two endpoints for creating and updating your email templates.
     response details: The response from this endpoint will include a field for email_template_id, which can be used to update the template in subsequent API calls.
etc. etc. 
```
(If none, leave blank, etc. you get the idea.)

### GET
- Endpoint name (will send list)
- Endpoint URL
- Method (POST, GET, Filter, Object) - obviously this will be all GET
- Description (write your own based on current docs)
- Parameters (include Data Type and Description beneath)
- Request Body Example
- Response Body Parameters
- Errors
- Corresponding Link to [Swagger](https://www.braze.com/docs/api/interactive/)
- Glossary Tags (see far below)

### Messaging & User Data Object Specification
This is specific to the [Messaging](https://www.braze.com/docs/api/endpoints/messaging/#messaging-objects--filters) & [User Data Endpoints](https://www.braze.com/docs/api/endpoints/user_data/#user-attributes-object-specification) and a note should be made about that. These are so far unnamed but documented [here](https://www.braze.com/docs/api/endpoints/messaging/#messaging-objects--filters). 
- Object Name
- Description
- Object Parameters
- Apple Button Object Default Buttons (breakdown beneath)

### Messaging Filters
This is specific to the [Messaging Endpoints](https://www.braze.com/docs/api/endpoints/messaging/#messaging-objects--filters) and a note should be made about that. These are so far unnamed but documented [here](https://www.braze.com/docs/api/endpoints/messaging/#messaging-objects--filters). 
- Filter Name
- Filter Component Name
- Method (POST, GET, Filter, Object) - obviously this will be all Filter
- Description (write your own based on current docs)
- Filter Fields
- Allowed Comparisons (comparison_1: Yadda, value_1: Yadda1)
- Example

#### Glossary Tags

These will create checkboxes that will help filter and narrow the endpoints for users.
- Email
- Export
- User Data
- Send Campaigns
- Schedule Campaigns
- Messaging
- GET Method
- POST Method
- Objects
- Filters

## A note on code and listing parameters in a code block

We'll take care of the final look, but you should format like this (query_parameter is an example field): 

query_parameter: "\\" 
    line 1
    line 2
    "

## Other Notes
- Sample: 
![Screen Shot 2019-06-03 at 4 51 42 PM](https://user-images.githubusercontent.com/25353255/58833951-2b987d00-8620-11e9-9cbe-6fab4341bba8.png)

**Comment by EmilyNecciai** [comment]
@zzhaobraze This is our Engineer - he can help you out.

**Comment by dnburtonguster** [comment]
Hi @zzhaobraze - I'm told the format for yaml fields is like so: query_parameter: "\"
line 1
line 2
"
 but front matter is quite particular. Where could I find all the custom yaml variables/fields, like 'response details', 'glossary tags', etc? Couldnt find them in the glossary.

Thanks

**Comment by zzhaobraze** [comment]
@dnburtonguster for this new process, the variables haven't been predefined yet, so you're essentially free to use whatever you want. i can modified them afterwards as needed as long as some simple conventions are used:

- don't use spaces or special characters besides underscore
- use lower case names
- end the variables name with a colon ( : ) 

You can see an example in Emily's description:

```
endpoint: Create Email Template
     endpoint_url: /templates/email/create
     method: POST
     description: Use the Email Template REST APIs to programmatically manage the email templates that you have stored on the Braze dashboard, on the Templates & Media page. Braze provides two endpoints for creating and updating your email templates.
     response details: The response from this endpoint will include a field for email_template_id, which can be used to update the template in subsequent API calls.
etc. etc. 
```


Tags can follow the glossary options where a global tag is defined with all possible values, and the tags are are also references individually under each set of information. Additional, a special keyword `All` can be used to reference all tags.

```
glossary_tags:
  - name: Content Cards
  - name: Email
  - name: In-App Message
  - name: News Feed
  - name: Web Push
  - name: iOS Push
  - name: Android Push
  - name: Webhook

glossaries:
  - name: Variation
    description: Variation of a campaign, differing as defined by the creator.
    calculation: Count
    tags:
      - All
 - name: Unique Recipients
    description: Exact number of users who received a particular message. This number is received from Braze.
    calculation: Count
    tags:
      - Email
      - Web Push
      - iOS Push
      - Android Push
      - In-App Message
      - News Feed
.......
```

Let me know if you have any additional questions or if you want more explicit variable names if that makes it easier for you.

Thanks

**Comment by dnburtonguster** [comment]
Ok thanks for the clarification; I thought they might already be defined somewhere..

**Comment by dnburtonguster** [comment]
Hey @zzhaobraze - I tried to push up a commit of a new branch up (to https://github.com/Appboy/braze-docs.git) to begin a PR, but I'm getting a 403 error..

**Comment by zzhaobraze** [comment]
What's the exact command you're using? 
you should be pushing to `git@github.com:Appboy/braze-docs.git` due to the security setting.  You need to have cloned the repo with SSH and not download it via https.

You can confirm with `git remote -v` 

You can try following these settings to resolve it:
https://help.github.com/en/articles/https-cloning-errors
https://www.a2hosting.com/kb/developer-corner/version-control-systems1/403-forbidden-error-message-when-you-try-to-push-to-a-github-repository
https://stackoverflow.com/questions/7438313/pushing-to-git-returning-error-code-403-fatal-http-request-failed

**Comment by dnburtonguster** [comment]
Thanks - I had an ssh key issue that needed fixing..
