### ISSUE TITLE
Improve Documentation around JS Bridges in HTML in app mesages 

### ISSUE THREAD

**Issue by georgiagh1991** [Appboy/braze-docs#219]
# Submit an Issue
**Describe the Problem:**
Our current documentation around how to use JS Bridges in HTML in app messages isn't very user friendly for CRM teams and out current github repo of HTML in app messages doesn't include JS bridges. As such, it makes the barrier to entry quite high. 

**Related Links, Resources, and Images:**
https://www.braze.com/docs/help/best_practices/in-app_messages/previous_in-app_message_generations/#web

https://github.com/Appboy/appboy-custom-html5-in-app-message-templates
**Code Samples:**

**Recommended Change Date:**

---
---

## Before You Submit

- [ ] Fill out the relevant items under __Submit an Issue__ above.
- [ ] [Label](https://github.com/Appboy/braze-docs/issues/labels) this issue.
- [ ] Assign this issue to either yourself, the Technical Writer (@EmilyNecciai), or to another appropriate person. _If you do not assign anyone to an issue, your issue may be closed._

---
---

---
---

[Docs Request Policy (Braze Internal Only)](https://confluence.braze.com/display/GROW/Request+Process)

**Comment by EmilyNecciai** [comment]
@dkim32 What are the possibilities of us adding in JS Bridges into the HTML repo? 

I'm not sure we should put a lot of effort into the "previous generation" docs...

**Comment by dkim32** [comment]
i would defer to @Bucimis @davidbielik

**Comment by davidbielik** [comment]
Done in https://github.com/Appboy/braze-docs/pull/879
