### ISSUE TITLE
Update images for advancement behavior

### ISSUE THREAD

**Issue by MarionNammack** [Appboy/braze-docs#232]
# Submit an Issue
**Describe the Problem:**
We changed the copy and some of the language for advancement behavior, and docs will need to be updated accordingly - images and probably some text too.
Would be good to have images of the copy in both expanded and collapsed state. 

"Advance If Message Received" => "Advance When Message Sent"

**Related Links, Resources, and Images:**
https://www.braze.com/docs/advancement_behavior/#advancement-behavior
**Code Samples:**

**Recommended Change Date:**
As soon as possible, but definitely needed by the July 30th major release.  
---
---

---
---

[Docs Request Policy (Braze Internal Only)](https://confluence.braze.com/display/GROW/Request+Process)

**Comment by MarionNammack** [comment]
@EmilyNecciai if the updates I just submitted are approved, we may be able to close this issue. I consolidated IAM/Advancement Behavior "To-Dos" in this issue: https://github.com/Appboy/braze-docs/issues/242

**Comment by EmilyNecciai** [comment]
Closed by #241
