### ISSUE TITLE
Update Frequency Capping Docs

### ISSUE THREAD

**Issue by MarionNammack** [Appboy/braze-docs#281]
# Submit an Issue
**Describe the Problem:**
As of yesterday, we updated our frequency capping logic so there's a part of docs that is out of date right now. 

https://www.braze.com/docs/frequency_capping_tag/ describes the correct behavior. 

https://www.braze.com/docs/user_guide/engagement_tools/campaigns/testing_and_more/rate-limiting/#frequency-capping is out of date, specifically: 
 Triggered in-app messages will count towards global frequency cap, however they cannot be frequency capped. For instance, an in-app message confirming a purchase will appear after every purchase regardless of frequency capping.

 Keep in mind that Frequency Capping applies to the campaigns a user receives, and not to individual messages. That is, if you have a recurring campaign that users are re-eligible to receive, each recurring message of each channel will be counted as just one campaign. For instance, if a user receives a recurring push campaign that delivers every day, and she is capped to 2 push campaigns per week, the recurring push messages will collectively count towards 1 push campaign for frequency capping purposes, and for that week, this user will still be eligible to receive a different campaign that contains push.

Both of these paragraphs are now incorrect and should be updated to describe the correct behavior.
**Related Links, Resources, and Images:**

**Code Samples:**

**Recommended Change Date:**

ASAP, since the info is not correct. 
---
---

## Before You Submit

- [ ] Fill out the relevant items under __Submit an Issue__ above.
- [ ] [Label](https://github.com/Appboy/braze-docs/issues/labels) this issue.
- [ ] Assign this issue to either yourself, the Technical Writer (@EmilyNecciai), or to another appropriate person. _If you do not assign anyone to an issue, your issue may be closed._

---
---

---
---

[Docs Request Policy (Braze Internal Only)](https://confluence.braze.com/display/GROW/Request+Process)

**Comment by EmilyNecciai** [comment]
Finished - closed with #286
