### ISSUE TITLE
remove apptimize

### ISSUE THREAD

**Issue by dkim32** [Appboy/braze-docs#366]
# Submit an Issue
**Describe the Problem:**
Remove apptimize as they were acquired by Airship.

**Related Links, Resources, Code Samples, and Images:**
https://www.braze.com/docs/partners/technology_partners/channel_extensions/ab_testing/apptimize/#apptimize

### Is this change associated with a Braze feature/product release?
- [ ] Yes (__Feature Release Date:__)
- [ ] No

> If yes, please note the date of the feature release.

---
---

## Before You Submit

- [ ] Fill out the relevant items under __Submit an Issue__ above.
- [ ] [Label](https://github.com/Appboy/braze-docs/issues/labels) this issue.
- [ ] Assign this issue to either yourself, the Technical Writer (@EmilyNecciai), or to another appropriate person. _If you do not assign anyone to an issue, your issue may be closed or left uncompleted._

---
---

---
---

[Docs Request Policy (Braze Internal Only)](https://confluence.braze.com/display/GROW/Request+Process)

**Comment by EmilyNecciai** [comment]
completed!
