### ISSUE TITLE
Unique Recipient Definition Seems Incorrect

### ISSUE THREAD

**Issue by MarionNammack** [Appboy/braze-docs#374]
https://www.braze.com/docs/user_guide/data_and_analytics/report_metrics/
I believe the description for unique recipients is wrong. Unique recipients are AFAIK, actually unique daily recipients. So the definition for content cards is actually how all of the unique recipient calculations work. This should be confirmed with data + analytics.

**Comment by toksfifo** [comment]
Confirmed

**Comment by MarionNammack** [comment]
Thank you @toksfifo
