### ISSUE TITLE
Update Cordova Docs for Geofences

### ISSUE THREAD

**Issue by radixdev** [Appboy/braze-docs#402]
# Submit an Issue
**Describe the Problem:**
Cordova Android/iOS docs need updates for Cordova SDK 2.11.0 which includes new geofences/location updates.

**Related Links, Resources, Code Samples, and Images:**

### Is this change associated with a Braze feature/product release?
- [ ] Yes (__Feature Release Date:__)
- [x] No

> If yes, please note the date of the feature release.

---
---

## Before You Submit

- [ ] Fill out the relevant items under __Submit an Issue__ above.
- [ ] [Label](https://github.com/Appboy/braze-docs/issues/labels) this issue.
- [x] Assign this issue to either yourself, the Technical Writer (@EmilyNecciai), or to another appropriate person. _If you do not assign anyone to an issue, your issue may be closed or left uncompleted._

---
---

---
---

[Docs Request Policy (Braze Internal Only)](https://confluence.braze.com/display/GROW/Request+Process)

**Comment by EmilyNecciai** [comment]
Hey @radixdev! Just wanted to check on this PR to see if it can be closed. Thanks!

**Comment by radixdev** [comment]
It can be! I thought my comment in #408 would automatically do it.
