### ISSUE TITLE
Update Create + Send Docs

### ISSUE THREAD

**Issue by MarionNammack** [Appboy/braze-docs#405]
# Submit an Issue
**Describe the Problem:**
The functionality described here: https://www.braze.com/docs/create_send/ is available in /canvas/trigger/send too! Could we update the docs and include the request body and an example for a Canvas?

Request Body: 

Same as https://www.braze.com/docs/api/endpoints/messaging/#sending-messages-via-api-triggered-delivery

but with: 
```
 "send_to_existing_only": (optional, boolean) defaults to true,
      "attributes": (optional, object) fields in the attributes object will create or update an attribute of that name with the given value on the specified user profile before the message is sent and existing values will be overwritten
```
After canvas_entry_properties

```
{
  "api_key": "YOUR_API_KEY",
  "canvas_id": "9398e4b5-0efd-bc7b-b545-d050f307ee91",
  "broadcast": false,
  "recipients": [
  {
  "external_user_id": "marebeare12345678",
  "send_to_existing_only": false,
   "attributes":
  	{
  	"first_name" : "Jon",
  	"email" : "marion+testing123456@braze.com",
  	"my_custom_attribute_string" : "value"
  	}
  }
]
}
```
is an example that works!

**Related Links, Resources, Code Samples, and Images:**

### Is this change associated with a Braze feature/product release?
- [ ] Yes (__Feature Release Date:__)
- [ X] No

> If yes, please note the date of the feature release.

---
---

## Before You Submit

---
---

---
---

[Docs Request Policy (Braze Internal Only)](https://confluence.braze.com/display/GROW/Request+Process)

**Comment by EmilyNecciai** [comment]
Complete!

**Comment by singhdharam112** [comment]
Hi @EmilyNecciai ,

I am able to use this but can you help me out on new user created subscription status.


Thanks,
