### ISSUE TITLE
Outdated Push Analytics Screenshot

### ISSUE THREAD

**Issue by EmilyNecciai** [Appboy/braze-docs#439]
# Submit an Issue
**Describe the Problem:**
The screenshot on this page appears to be from a few years back. Since then the design has changed and also some additional fields were added, for example influenced opens.
https://www.braze.com/docs/user_guide/message_building_by_channel/push/creating_a_push_message/#results-data-push

**Related Links, Resources, Code Samples, and Images:**
https://www.braze.com/docs/user_guide/message_building_by_channel/push/creating_a_push_message/#results-data-push

### Is this change associated with a Braze feature/product release?
- [ ] Yes (__Feature Release Date:__)
- [ ] No

> If yes, please note the date of the feature release.

---
---

## Before You Submit

- [ ] Fill out the relevant items under __Submit an Issue__ above.
- [ ] [Label](https://github.com/Appboy/braze-docs/issues/labels) this issue.
- [ ] Assign this issue to either yourself, the Technical Writer (@EmilyNecciai), or to another appropriate person. _If you do not assign anyone to an issue, your issue may be closed or left uncompleted._

---
---

---
---

[Docs Request Policy (Braze Internal Only)](https://confluence.braze.com/display/GROW/Request+Process)

**Comment by Lawrence4code** [comment]
I'd like to work on this, please.

**Comment by Lawrence4code** [comment]
@EmilyNecciai Thanks for the opportunity.
Could you please guide me where I can get the screenshots from. I reviewed the codebase and site, I wasn't able to sign up or able to get demo user credential in order to get the place where I can take the screenshot. Thanks in advance.

**Comment by EmilyNecciai** [comment]
Hi @Lawrence4code, this might be something only people with accounts can do. Sorry about that! I'm going to be adding a few more issues soon that aren't dependent on account access.
