### ISSUE TITLE
Documentation for "Day of Recurring Event" Filter Updates

### ISSUE THREAD

**Issue by MarionNammack** [Appboy/braze-docs#714]
# Submit an Issue
**Describe the Problem:**
We're making updates to filter behavior, and would like to create documentation that explains the changes and documents the expected behavior of the filters. Expected behavior is detailed here: https://confluence.braze.com/display/MES/Custom+Attribute+Filter+Communication+Plan

The URL that the dashboard feature links to is: https://www.braze.com/docs/day-of-custom-attribute-behavior, however if you prefer to make a page that isn't hidden, just let me know so that I can update the docs accordingly. 

**Related Links, Resources, Code Samples, and Images:**

### Is this change associated with a Braze feature/product release?
- [X ] Yes (__Feature Release Date: Jan 14)
- [ ] No

> If yes, please note the date of the feature release.

---
---

## Before You Submit

- [ ] Fill out the relevant items under __Submit an Issue__ above.
- [ ] [Label](https://github.com/Appboy/braze-docs/issues/labels) this issue.
- [ ] Assign this issue to either yourself, the Technical Writer (@EmilyNecciai), or to another appropriate person. _If you do not assign anyone to an issue, your issue may be closed or left uncompleted._

---
---

---
---

[Docs Request Policy (Braze Internal Only)](https://confluence.braze.com/display/GROW/Request+Process)

**Comment by KellieHawks** [comment]
Waiting on review from Marion for https://github.com/Appboy/braze-docs/pull/822 until this gets closed.
