### ISSUE TITLE
Edits for Canvas In-App Message Docs 

### ISSUE THREAD

**Issue by MarionNammack** [Appboy/braze-docs#87]
# Submit an Issue
**Describe the Problem:**
I want to clarify the following in the Canvas in-app message docs: 

- Action-based delivery is not available for Canvas steps with in-app messages. Canvas steps with in-app messages must be scheduled. 
- Canvas in-app messages will appear the first time that a user opens their app after the step has been sent to them.

**Recommended Change Date:** Tuesday, May 7. 

---
---

---
---

---
---

[Docs Request Policy (Braze Internal Only)](https://confluence.braze.com/display/GROW/Request+Process)

**Comment by EmilyNecciai** [comment]
@MarionNammack Is this a necessary change for May 7th? If not, I'm going to move it to the week after to concentrate on the Product Release.
