### ISSUE TITLE
Typo in certain URL redirects

### ISSUE THREAD

**Issue by andrewtremblay** [Appboy/braze-docs#911]
There is a typo in some of the URLs that are being redirected on the following page: 

https://www.braze.com/docs/partners/data_and_infrastructure_agility/

Clicking on any of the big cloud storage options (Amazon, Google cloud, or Azure) redirects to a 404 page.

https://www.braze.com/docs/partners/data_and_infrastructure_agility/data_warehouses/amazon_s3/ ~> https://www.braze.com/docs/partners/data_and_infrastructure_agility/coud_storage/amazon_s3/?redirected=true

https://www.braze.com/docs/partners/data_and_infrastructure_agility/data_warehouses/google_cloud_storage_for_currents/ ~>  https://www.braze.com/docs/partners/data_and_infrastructure_agility/coud_storage/google_cloud_storage_for_currents/?redirected=true

https://www.braze.com/docs/partners/data_and_infrastructure_agility/data_warehouses/microsoft_azure_blob_storage_for_currents/ ~> https://www.braze.com/docs/partners/data_and_infrastructure_agility/coud_storage/microsoft_azure_blob_storage_for_currents/?redirected=true

In the URL, `coud_storage` should be `cloud_storage`.

**Comment by KellieHawks** [comment]
Hello @andrewtremblay , thanks for bringing up this issue. This has been dealt with as of 2/7/20, and you will see the changes in our next documentation deploy, Tuesday 2/11/20 end of day. Thanks for the feedback!

-The Documentation Team @ Braze
